name: image_cropper
description: A Flutter plugin for Android, iOS and Web supports cropping images
version: 9.1.0
homepage: https://github.com/hnvn/flutter_image_cropper

environment:
  sdk: '>=3.3.0 <4.0.0'
  flutter: '>=1.20.0'

flutter:
  plugin:
    platforms:
      android:
        package: com.yalantis.ucrop.imagecropper
        pluginClass: ImageCropperPlugin
      ios:
        pluginClass: FLTImageCropperPlugin

dependencies:
  flutter:
    sdk: flutter
  image_cropper_platform_interface: ^7.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  plugin_platform_interface: ^2.1.8
